### ISSUE TITLE
Enterprise Features

### ISSUE THREAD

**Issue by hypostulate** [jvrana/benchling-api#38]
**Proposal**
Extend features to cover enterprise use-cases including requests, workflows, transfers, inventory management, warehouse, and (soon) "automation"

**Rationale**
A large number of "quiet" users require integrations with these API endpoints, and constructing simple integration APIs is non-trivial. Extending the object-oriented framework here would make developing these integrations much easier.

**Caveats**
One hurdle is that of testing, without access to the features we would need to develop a mocking suite capable of recapitulating the API response.

**Potential Solution**
Reach out to Benchling directly about setting up a development environment with enterprise features. They have contributed some examples to github and may be receptive.

I'd be happy to chip away at some of these implementations, but would like some guidance on structure and test design to follow the style in place. For example, many of these endpoints can have many (hundreds) of various API actions in a single "unit". I'd be interested in hearing some design ideas for expanding the data model to the enterprise features.

**Comment by jvrana** [comment]
This sounds like a great idea. I haven't used the enterprise features myself, and so I'm curious at what this looks like and I'm happy to help with guidance on the structure. I can explain more in detail in this issue thread, as well as fill out this documentation page a bit more (http://klavinslab.org/benchling-api/guidelines.html). I think building out these models should be quick, developing the testing fixtures will take a bit more time.

Let's do contact Benchling about getting some kind of development-enterprise account. I'll do this now and report back here.

**Comment by borosilicate** [comment]
@jvrana any updates?

**Comment by hypostulate** [comment]
@borosilicate I would check out the [benchling-sdk](https://docs.benchling.com/docs/getting-started-with-the-sdk). Given Benchling is supporting this directly, and it is being largely auto-generated from their API configuration, it is always going to be more up to date than any third party library. I think there is significant room for expanding on top of their SDK library (for multi-endpoint integrations, etc), but for basic API client usage, their SDK is becoming the standard.
